/// Pure sensitivity predicate for `NSPasteboard` items (CLIP-01/D-15). No
/// AppKit import — the caller maps `pasteboardItem.types.map(\.rawValue)`
/// before calling `isSensitive(declaredTypes:)`.
///
/// Source: nspasteboard.org — https://nspasteboard.org/ (the open community
/// spec every serious macOS clipboard manager, including 1Password, opts
/// into) [CITED: nspasteboard.org, HIGH — primary source].
public enum ClipboardSensitivity {
    public static let markerTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    public static func isSensitive(declaredTypes: [String]) -> Bool {
        !markerTypes.isDisjoint(with: Set(declaredTypes))
    }
}
