import Testing
@testable import MyIslandCore

@Test func isSensitiveDetectsConcealedType() {
    #expect(ClipboardSensitivity.isSensitive(declaredTypes: ["org.nspasteboard.ConcealedType"]))
}

@Test func isSensitiveDetectsTransientType() {
    #expect(ClipboardSensitivity.isSensitive(declaredTypes: ["org.nspasteboard.TransientType"]))
}

@Test func isSensitiveDetectsAutoGeneratedType() {
    #expect(ClipboardSensitivity.isSensitive(declaredTypes: ["org.nspasteboard.AutoGeneratedType"]))
}

@Test func isSensitiveIsFalseForOrdinaryText() {
    #expect(!ClipboardSensitivity.isSensitive(declaredTypes: ["public.utf8-plain-text"]))
}

@Test func isSensitiveIsFalseForEmptyTypes() {
    #expect(!ClipboardSensitivity.isSensitive(declaredTypes: []))
}

@Test func isSensitiveIsTrueWhenMarkerMixedWithOrdinaryText() {
    #expect(ClipboardSensitivity.isSensitive(declaredTypes: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]))
}
